
meeting_gpu_worker  | [NeMo W 2025-09-17 16:42:16 nemo_logging:405] If you intend to do validation, please call the ModelPT.setup_validation_data() or ModelPT.setup_multiple_validation_data() method and provide a valid configuration file to setup the validation data loader(s).
meeting_gpu_worker  |     Validation config :
meeting_gpu_worker  |     manifest_filepath: /manifests/combined_fisher_swbd_voxceleb12_librispeech/dev.json
meeting_gpu_worker  |     sample_rate: 16000
meeting_gpu_worker  |     labels: null
meeting_gpu_worker  |     batch_size: 128
meeting_gpu_worker  |     shuffle: false
meeting_gpu_worker  |     num_workers: 15
meeting_gpu_worker  |     pin_memory: true
meeting_gpu_worker  |
meeting_gpu_worker  | [NeMo I 2025-09-17 16:42:16 nemo_logging:393] PADDING: 16
meeting_api_server  | 2025-09-17 16:42:17,514 - INFO - httpx - HTTP Request: POST http://10.43.128.107:7333/collections/meeting_speakers/points/scroll "HTTP/1.1 200 OK"
meeting_api_server  | INFO:     192.168.16.4:40988 - "POST /api/v1/speaker/ HTTP/1.1" 409 Conflict
meeting_gpu_worker  | [NeMo I 2025-09-17 16:42:17 nemo_logging:393] Model EncDecSpeakerLabelModel was successfully restored from /project/diarization_service/models/rimecaster.nemo.
meeting_gpu_worker  | [2025-09-17 16:42:17,935: INFO/MainProcess] Speaker Embedding model '/project/diarization_service/models/rimecaster.nemo' loaded successfully.
meeting_gpu_worker  | [2025-09-17 16:42:18,020: WARNING/MainProcess] Could not process or get embedding for sample /code/shared_audio/enrollment_samples/takeos/9ac2ac58-0da6-4456-aa51-7b71fd87ef5f_TV HDQT Takeo Shimotsu.mp3: 'NoneType' object has no attribute 'get_embedding'
meeting_gpu_worker  | [2025-09-17 16:42:18,020: ERROR/MainProcess] [Task] Enrollment failed for 'takeos': Enrollment failed for 'takeos': No valid embeddings could be extracted from samples.
meeting_gpu_worker  | Traceback (most recent call last):
meeting_gpu_worker  |   File "/code/app/worker/tasks.py", line 188, in enroll_speaker_task
meeting_gpu_worker  |     enrollment_svc.enroll_new_speaker(
meeting_gpu_worker  |   File "/code/app/processing/enrollment.py", line 148, in enroll_new_speaker
meeting_gpu_worker  |     raise ValueError(f"Enrollment failed for '{user_ad}': No valid embeddings could be extracted from samples.")
meeting_gpu_worker  | ValueError: Enrollment failed for 'takeos': No valid embeddings could be extracted from samples.
meeting_gpu_worker  | [2025-09-17 16:42:18,029: ERROR/MainProcess] Task enroll_speaker_task[dfe5b1de-7fd1-4d2d-ac10-50294a941da4] raised unexpected: ValueError("Enrollment failed for 'takeos': No valid embeddings could be extracted from samples.")
meeting_gpu_worker  | Traceback (most recent call last):
meeting_gpu_worker  |   File "/usr/local/lib/python3.12/dist-packages/celery/app/trace.py", line 453, in trace_task
meeting_gpu_worker  |     R = retval = fun(*args, **kwargs)
meeting_gpu_worker  |                  ^^^^^^^^^^^^^^^^^^^^
meeting_gpu_worker  |   File "/usr/local/lib/python3.12/dist-packages/celery/app/trace.py", line 736, in __protected_call__
meeting_gpu_worker  |     return self.run(*args, **kwargs)
meeting_gpu_worker  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
meeting_gpu_worker  |   File "/code/app/worker/tasks.py", line 188, in enroll_speaker_task
meeting_gpu_worker  |     enrollment_svc.enroll_new_speaker(
meeting_gpu_worker  |   File "/code/app/processing/enrollment.py", line 148, in enroll_new_speaker
meeting_gpu_worker  |     raise ValueError(f"Enrollment failed for '{user_ad}': No valid embeddings could be extracted from samples.")
meeting_gpu_worker  | ValueError: Enrollment failed for 'takeos': No valid embeddings could be extracted from samples.
